#!/bin/sh

echo "Running git pre-commit hook"

./gradlew app:ktlintCheck app:detekt --daemon

STATUS=$?

# TODO: improve this script to be more informative
# return 1 exit code if running check fails
[ $STATUS -ne 0 ] && exit 1
exit 0
