name: Android Build Deployment

on:
  push:
    branches:
      - develop
      - master

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Set up Ruby and Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true

      - name: Set up Encrypted Keystore File
        run: |
          mkdir -p release
          echo "${{ secrets.ENCRYPTED_KEYSTORE_CONTENT }}" > release/encrypted_keystore.enc

      - name: Decrypt Keystore
        run: |
          base64 -d -i release/encrypted_keystore.enc | \
          openssl enc -d -aes-256-cbc -pbkdf2 \
          -pass pass:"${{ secrets.ENCRYPTED_KEYSTORE_PASSPHRASE }}" \
          -out ../release/dailyscoop-keystore.jks

      - name: Set up local.properties
        run: |
          cat <<EOF > $GITHUB_WORKSPACE/local.properties
          NEWS_API_KEY=${{ secrets.NEWS_API_KEY }}
          KEY_STORE_ALIAS=${{ secrets.SIGNING_KEY_ALIAS }}
          KEY_STORE_PASSWORD=${{ secrets.SIGNING_STORE_PASSWORD }}
          KEY_STORE_KEY_PASSWORD=${{ secrets.SIGNING_KEY_PASSWORD }}
          EOF

      - name: Build and Test
        run: ./gradlew build

      - name: Run All Unit Tests
        id: test
        run: ./gradlew test

      - name: Run Android Linter
        id: lint
        run: ./gradlew lint --stacktrace

      - name: Run Code Analyzers
        id: analyzers
        run: ./gradlew ktlintCheck detekt

      - name: Deploy Android Build
        env:
          SLACK_DEPLOYMENT_WEBHOOK_URL: ${{ secrets.SLACK_DEPLOYMENT_WEBHOOK_URL }}
        run: |
          if [ "$GITHUB_REF" = "refs/heads/develop" ]; then
            bundle exec fastlane dev
          elif [ "$GITHUB_REF" = "refs/heads/master" ]; then
            bundle exec fastlane live
          fi

      - name: Determine APK Path and Artifact Name
        run: |
          if [ "$GITHUB_REF" = "refs/heads/develop" ]; then
            flavor="dev"
          elif [ "$GITHUB_REF" = "refs/heads/master" ]; then
            flavor="live"
          else
            flavor="unknown"
          fi

          echo "APK_PATH=$GITHUB_WORKSPACE/app/build/outputs/apk/${flavor}/release/app-${flavor}-release.apk" >> $GITHUB_ENV
          echo "ARTIFACT_NAME=Daily Scoop - Android - ${flavor^^}" >> $GITHUB_ENV

      - name: Upload Build as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ env.APK_PATH }}

