name: Review

on:
  pull_request:
    branches:
      - master
      - dev
      - review

jobs:
  review:
    name: Review Android PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 17

      - uses: gradle/gradle-build-action@v2
        with:
            cache-disabled: true

      - name: Run All Unit Tests
        id: test
        run: ./gradlew test

      - name: Run Android Linter
        id: lint
        run: ./gradlew lint --stacktrace

      - name: Run Code Analyzers
        id: analyzers
        run: ./gradlew ktlintCheck detektº

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,action,eventName,ref,workflow,pullRequest # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

