name: Review

on:
  pull_request:
    branches:
      - master
      - dev
      - review

jobs:
  review:
    name: Review Android PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build Project
        run: ./gradlew assemble

      - name: Run All Tests
        run: ./gradlew test
        
      - name: Run Android Linter
        run: ./gradlew lint --stacktrace

      - name: Run Code Analyzers
        run: ./gradlew ktlintCheck detekt
