name: Review

on:
  pull_request:
    branches:
      - master
      - dev
      - review

jobs:
  review:
    name: Review Android PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Gradle Cache
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up local.properties
        run: |
          echo "api_key=$API_KEY" >> $GITHUB_WORKSPACE/local.properties
        env:
          API_KEY: ${{ '' }}

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Build Project
        id: build
        run: ./gradlew assemble

      - name: Run All Tests
        id: test
        run: ./gradlew test

      - name: Run Android Linter
        id: lint
        run: ./gradlew lint --stacktrace

      - name: Run Code Analyzers
        id: analyzers
        run: ./gradlew ktlintCheck detekt

      - name: Create Check Runs
        uses: peter-evans/create-check@v1
        with:
          name: Results
          conclusion: success
          output: |
            - title: Build
              summary: ${{ job.steps.build.conclusion }}
            - title: Tests
              summary: ${{ job.steps.test.conclusion }}
            - title: Code Quality Analyzers
              summary: ${{ job.steps.lint.conclusion }} & ${{ job.steps.analyzers.conclusion }}

      - name: Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: |
                  ${process.env.GITHUB_WORKFLOW}
                  ${process.env.GITHUB_JOB} (${process.env.GITHUB_SHA}) of ${process.env.GITHUB_REPOSITORY}@${process.env.GITHUB_REF}
                  by ${process.env.GITHUB_ACTOR}
                  ${{ job.status }} in ${{ job.completed_at }}
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

