name: Review

on:
  pull_request:
    branches:
      - master
      - dev
      - review

jobs:
  review:
    name: Review Android PR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'

      - name: Build Project
        run: ./gradlew assemble

      - name: Run Tests
        run: ./gradlew test

      - name: Run Code Analyzers
        run: ./gradlew ktlintCheck detekt
