@file:Suppress("LargeClass", "MaxLineLength")

package app.daily.scoop.fake

import app.daily.scoop.data.network.models.ArticleDto
import app.daily.scoop.model.Article
import app.daily.scoop.model.Headline

object FakeDataSource {

    val localHeadline1 = Headline(
        id = 1,
        title = "F1: Max Verstappen wins US Grand Prix",
        topic = "news",
        publishedDate = "2022-10-24 23:45:30",
        mediaUrl = "https://sports.inquirer.net/files/2022/10/2022-10-24T015205Z_1_LYNXMPEI9N01J_RTROPTP_4_MOTOR-F1-USA-scaled.jpg",
        externalId = "2665f479d34776dc7220786ce0658b58"
    )

    val localHeadline2 = Headline(
        id = 2,
        title = "NBA: Anthony Edwards, Timberwolves blow by Thunder",
        topic = "news",
        publishedDate = "2022-10-24 23:38:07",
        mediaUrl = "https://sports.inquirer.net/files/2022/10/063_1244093160.jpg",
        externalId = "57fe599411e31393e29111b6510c8460"
    )

    val localNewsArticle2 = Article(
        id = 2,
        title = "NBA: Anthony Edwards, Timberwolves blow by Thunder",
        author = "Reuters",
        excerpt = "Anthony Edwards scored 30 points and grabbed 11 rebounds to lead the Minnesota Timberwolves to a 116-106 win over the host Oklahoma City Thunder on Sunday night. The Timberwolves led by as many",
        summary = "Anthony Edwards #1 of the Minnesota Timberwolves dribbles the ball while Josh Giddey #3 of the Oklahoma City Thunder defends in the fourth quarter of the game at Target Center on October 19, 2022 in Minneapolis, Minnesota. The Timberwolves defeated the Thunder 115-108. David Berding/Getty Images/AFP\nAnthony Edwards scored 30 points and grabbed 11 rebounds to lead the Minnesota Timberwolves to a 116-106 win over the host Oklahoma City Thunder on Sunday night.\nThe Timberwolves led by as many 18 early, but the Thunder steadily cut the deficit to as little as one by late in the third quarter.",
        topic = "news",
        publishedDate = "2022-10-24 23:38:07",
        originalNewsLink = "https://sports.inquirer.net/?p=482565",
        sourceLink = "inquirer.net",
        mediaUrl = "https://sports.inquirer.net/files/2022/10/063_1244093160.jpg",
        externalId = "57fe599411e31393e29111b6510c8460"
    )

    val remoteNewsArticles = listOf(
        ArticleDto(
            id = "2665f479d34776dc7220786ce0658b58",
            title = "F1: Max Verstappen wins US Grand Prix",
            author = "Reuters",
            publishedDate = "2022-10-24 23:45:30",
            publishedDatePrecision = "timezone unknown",
            link = "https://sports.inquirer.net/?p=482568",
            cleanUrl = "inquirer.net",
            excerpt = "Max Verstappen fought back from a slow pitstop to win the US Grand Prix in Austin on Sunday as his Red Bull team clinched the Formula One constructors' title a day after the death of",
            summary = "Formula One F1 – United States Grand Prix – Circuit of the Americas, Austin, Texas, U.S. – October 23, 2022 Red Bull team principal Christian Horner, advisor Helmut Marko, Max Verstappen, Sergio Perez, Red bull team and staff celebrate winning the constructors championship REUTERS/Mike Segar\nMax Verstappen fought back from a slow pitstop to win the US Grand Prix in Austin on Sunday as his Red Bull team clinched the Formula One constructors' title a day after the death of billionaire owner Dietrich Mateschitz.",
            rights = "inquirer.net",
            rank = 1957,
            topic = "news",
            country = "PH",
            language = "en",
            authors = "Reuters",
            mediaUrl = "https://sports.inquirer.net/files/2022/10/2022-10-24T015205Z_1_LYNXMPEI9N01J_RTROPTP_4_MOTOR-F1-USA-scaled.jpg",
            isOpinion = false,
            twitterAccount = null,
            score = null
        ),
        ArticleDto(
            id = "57fe599411e31393e29111b6510c8460",
            title = "NBA: Anthony Edwards, Timberwolves blow by Thunder",
            author = "Reuters",
            publishedDate = "2022-10-24 23:38:07",
            publishedDatePrecision = "timezone unknown",
            link = "https://sports.inquirer.net/?p=482565",
            cleanUrl = "inquirer.net",
            excerpt = "Anthony Edwards scored 30 points and grabbed 11 rebounds to lead the Minnesota Timberwolves to a 116-106 win over the host Oklahoma City Thunder on Sunday night. The Timberwolves led by as many",
            summary = "Anthony Edwards #1 of the Minnesota Timberwolves dribbles the ball while Josh Giddey #3 of the Oklahoma City Thunder defends in the fourth quarter of the game at Target Center on October 19, 2022 in Minneapolis, Minnesota. The Timberwolves defeated the Thunder 115-108. David Berding/Getty Images/AFP\nAnthony Edwards scored 30 points and grabbed 11 rebounds to lead the Minnesota Timberwolves to a 116-106 win over the host Oklahoma City Thunder on Sunday night.\nThe Timberwolves led by as many 18 early, but the Thunder steadily cut the deficit to as little as one by late in the third quarter.",
            rights = "inquirer.net",
            rank = 1957,
            topic = "news",
            country = "PH",
            language = "en",
            authors = "Reuters",
            mediaUrl = "https://sports.inquirer.net/files/2022/10/063_1244093160.jpg",
            isOpinion = false,
            twitterAccount = null,
            score = null
        )
    )

    val remoteNewsData = """
        {
          "status": "ok",
          "total_hits": 909,
          "page": 1,
          "total_pages": 19,
          "page_size": 50,
          "articles": [
            {
              "title": "F1: Max Verstappen wins US Grand Prix",
              "author": "Reuters",
              "published_date": "2022-10-24 23:45:30",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482568",
              "clean_url": "inquirer.net",
              "excerpt": "Max Verstappen fought back from a slow pitstop to win the US Grand Prix in Austin on Sunday as his Red Bull team clinched the Formula One constructors' title a day after the death of",
              "summary": "Formula One F1 – United States Grand Prix – Circuit of the Americas, Austin, Texas, U.S. – October 23, 2022 Red Bull team principal Christian Horner, advisor Helmut Marko, Max Verstappen, Sergio Perez, Red bull team and staff celebrate winning the constructors championship REUTERS/Mike Segar\nMax Verstappen fought back from a slow pitstop to win the US Grand Prix in Austin on Sunday as his Red Bull team clinched the Formula One constructors' title a day after the death of billionaire owner Dietrich Mateschitz.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/2022-10-24T015205Z_1_LYNXMPEI9N01J_RTROPTP_4_MOTOR-F1-USA-scaled.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "2665f479d34776dc7220786ce0658b58"
            },
            {
              "title": "NBA: Anthony Edwards, Timberwolves blow by Thunder",
              "author": "Reuters",
              "published_date": "2022-10-24 23:38:07",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482565",
              "clean_url": "inquirer.net",
              "excerpt": "Anthony Edwards scored 30 points and grabbed 11 rebounds to lead the Minnesota Timberwolves to a 116-106 win over the host Oklahoma City Thunder on Sunday night. The Timberwolves led by as many",
              "summary": "Anthony Edwards #1 of the Minnesota Timberwolves dribbles the ball while Josh Giddey #3 of the Oklahoma City Thunder defends in the fourth quarter of the game at Target Center on October 19, 2022 in Minneapolis, Minnesota. The Timberwolves defeated the Thunder 115-108. David Berding/Getty Images/AFP\nAnthony Edwards scored 30 points and grabbed 11 rebounds to lead the Minnesota Timberwolves to a 116-106 win over the host Oklahoma City Thunder on Sunday night.\nThe Timberwolves led by as many 18 early, but the Thunder steadily cut the deficit to as little as one by late in the third quarter.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/063_1244093160.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "57fe599411e31393e29111b6510c8460"
            },
            {
              "title": "NBA: Depleted Hornets sting Hawks",
              "author": "Reuters",
              "published_date": "2022-10-24 23:29:09",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482562",
              "clean_url": "inquirer.net",
              "excerpt": "Shorthanded Charlotte got a career-high 20 points and 11 rebounds from Nick Richards and the visiting Hornets beat Atlanta 126-109 on Sunday to hand the Hawks their first loss. Richards was one",
              "summary": "Kelly Oubre Jr. #12 of the Charlotte Hornets brings the ball up court against the New Orleans Pelicans during their game at Spectrum Center on October 21, 2022 in Charlotte, North Carolina. Jacob Kupferman/Getty Images/AFP\nShorthanded Charlotte got a career-high 20 points and 11 rebounds from Nick Richards and the visiting Hornets beat Atlanta 126-109 on Sunday to hand the Hawks their first loss.\nRichards was one of six players to score in double figures for the Hornets, who were playing without leading scorer Terry Rozier (right ankle sprain), Cody Martin (left quad soreness) and LaMelo Ball (left ankle sprain).",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/063_1435589361.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "0b6eac3ed43e5a4656e691fc74b02838"
            },
            {
              "title": "Oil firms to implement rollback starting Oct. 25",
              "author": "Dhne Galvez",
              "published_date": "2022-10-24 23:27:03",
              "published_date_precision": "timezone unknown",
              "link": "https://business.inquirer.net/369242/oil-firms-to-implement-small-time-rollback-starting-oct-25",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — Local oil firms are set to implement minimal rollbacks in fuel prices —ranging from P0.35 per liter to P1.10 per liter-- starting Tuesday, Oct. 25. In separate advisories",
              "summary": "MANILA, Philippines — Local oil firms are set to implement minimal rollbacks in fuel prices —ranging from P0.35 per liter to P1.10 per liter– starting Tuesday, Oct. 25.\nIn separate advisories on Monday, the following oil firms announced their respective price adjustments starting Tuesday:\nShell (6 a.m.)\nGasoline: -P0.35 per liter\nKerosene: -P0.45 per liter\nDiesel: -P1.10 per liter\nPetro Gazz (6a.m.)\nGasoline: -P0.35 per liter\nDiesel: -P1.10 per liter\nSeaoil (6 a.m.)\nGasoline: -P0.35 per liter\nKerosene: -P0.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Daphne Galvez",
              "media": "https://business.inquirer.net/files/2016/01/Oil-Prices-Stock-Market.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "abed7d06d6cf1f8f9f026c7d4aa553e3"
            },
            {
              "title": "NBA: Donovan Mitchell breaks franchise record in Cavaliers' OT win over Wizards",
              "author": "Reuters",
              "published_date": "2022-10-24 23:22:30",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482559",
              "clean_url": "inquirer.net",
              "excerpt": "Donovan Mitchell scored 37 points to lift the host Cleveland Cavaliers to a 117-107 overtime victory over the Washington Wizards on Sunday. Mitchell has a franchise-record three straight games",
              "summary": "Donovan Mitchell #45 of the Cleveland Cavaliers reacts during the second quarter against the Washington Wizards at Rocket Mortgage Fieldhouse on October 23, 2022 in Cleveland, Ohio. Jason Miller/Getty Images/AFP\nDonovan Mitchell scored 37 points to lift the host Cleveland Cavaliers to a 117-107 overtime victory over the Washington Wizards on Sunday.\nMitchell has a franchise-record three straight games of at least 30 points to start the season. The offseason acquisition's 100 points are the most by a Cleveland player since Austin Carr scored 90 in 1974-75.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/063_1436004250.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "88d7b092d9f14d704ef3337282174b70"
            },
            {
              "title": "Vanuatu elects first woman MP in 14 years",
              "author": "Agence France-Presse",
              "published_date": "2022-10-24 23:21:34",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/?p=1684149",
              "clean_url": "inquirer.net",
              "excerpt": "Port Vila, Vanuatu — Vanuatu has elected the first woman to its parliament in 14 years, official results of a snap election showed Monday. Gloria Julia King will be the only woman in the",
              "summary": "Vanuatu flag (FILE PHOTO)\nPort Vila, Vanuatu — Vanuatu has elected the first woman to its parliament in 14 years, official results of a snap election showed Monday.\nGloria Julia King will be the only woman in the 52-member legislature, the Vanuatu Electoral Office said, after a half dozen other female candidates failed to secure a seat.\nKing's electoral success comes after a colorful career, playing international football and co-running a business selling kava — the peppery, mildly intoxicating root drink that is a vital part of Pacific ceremonies.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Agence France-Presse",
              "media": "https://newsinfo.inquirer.net/files/2022/10/Vanuatu-flag-filephoto-102422-620x349.png",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "8803a03a7197176b8a13bf5950430338"
            },
            {
              "title": "Kuh Ledesma, Odette Quesada, and Fe Delos Reyes fill Newport World Resorts with love",
              "author": "Cai Ordinario",
              "published_date": "2022-10-24 23:16:43",
              "published_date_precision": "full",
              "link": "https://businessmirror.com.ph/2022/10/25/kuh-ledesma-odette-quesada-and-fe-delos-reyes-fill-newport-world-resorts-with-love/",
              "clean_url": "businessmirror.com.ph",
              "excerpt": "Time and again, Kuh Ledesma proves her prowess as a singer, with an endless passion for music like a love that knows no limit. The Philippine pop diva is touching the hearts of audiences with 'All…",
              "summary": "Time and again, Kuh Ledesma proves her prowess as a singer, with an endless passion for music like a love that knows no limit. The Philippine pop diva is touching the hearts of audiences with 'All About Love', a two-night concert on December 2 & 3, 2022, 8 PM at the Newport Performing Arts Theater. Along with notable OPM icons of their generation, Odette Quesada and Fe De Los Reyes join her live onstage as they perform timeless hits and relive their glory days. After the recent success of the 'All About Love' Las Vegas show, the vocal trio now bring spectacular performances to fans here at home.",
              "rights": "businessmirror.com.ph",
              "rank": 14109,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Cai Ordinario,Patrick V. Miguel,Rick Olivares,SoundStrip,Tony M. Maghirang",
              "media": "https://businessmirror.com.ph/wp-content/uploads/2022/10/20221024_Press-Release_All-About-Love.jpg",
              "is_opinion": false,
              "twitter_account": "@businessmirror",
              "_score": null,
              "_id": "54063edf44519c3fd1d02ce0d3ebae53"
            },
            {
              "title": "NATO warns Russia against 'dirty bomb' pretext",
              "author": "If Storyparsed.Issaf",
              "published_date": "2022-10-24 23:15:51",
              "published_date_precision": "full",
              "link": "https://www.gmanetwork.com/news/topstories/world/849156/nato-warns-russia-against-dirty-bomb-pretext/story/",
              "clean_url": "gmanetwork.com",
              "excerpt": "Russia must not escalate the conflict in Ukraine with false claims that Kyiv is planning to unleash a so-called \"dirty bomb\", the head of NATO warned Monday.",
              "summary": "Published October 25, 2022 7:15am BRUSSELS, Belgium - Russia must not escalate the conflict in Ukraine with false claims that Kyiv is planning to unleash a so-called \"dirty bomb\", the head of NATO warned Monday. Jens Stoltenberg weighed in following Moscow's repeated allegations that Ukraine could deploy such a weapon, sparking fears Russia could use one and blame Kyiv. The head of the US-led military alliance said he had spoken with Pentagon chief Lloyd Austin and Britain's Defense Secretary Ben Wallace \"about Russia's false claim that Ukraine is preparing to use a dirty bomb on its own territory.",
              "rights": " Copyright 2022 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
              "rank": 5469,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "AFP,GMA News Online,If Storyparsed.Issaf,If Storyparsed.Storyobj.Brand",
              "media": "https://images.gmanews.tv/webpics/2021/08/russia_flag_2021_08_31_23_06_05.jpg",
              "is_opinion": false,
              "twitter_account": "@GMANewsOnline",
              "_score": null,
              "_id": "8c8a729aeb93a3066b53dea0f01578a4"
            },
            {
              "title": "Biden to get updated COVID-19 vaccine, urge Americans to follow suit",
              "author": "Reuters",
              "published_date": "2022-10-24 23:12:49",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/?p=1684145",
              "clean_url": "inquirer.net",
              "excerpt": "U.S. President Joe Biden will get his updated COVID-19 vaccine on Tuesday and urge more Americans to get the latest shot, White House spokesman Kevin Munoz said on Sunday. Only 20 million",
              "summary": "U.S. President Joe Biden holds a face mask during a meeting with members of the White House COVID-19 Response Team on the latest developments related to the Omicron variant of the coronavirus in the South Court Auditorium at the White House complex in Washington, U.S., January 4, 2022. REUTERS FILE PHOTO\nU.S. President Joe Biden will get his updated COVID-19 vaccine on Tuesday and urge more Americans to get the latest shot, White House spokesman Kevin Munoz said on Sunday.\nOnly 20 million people in the United States have received an updated COVID vaccine through last week.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://newsinfo.inquirer.net/files/2022/10/Joe-Biden-620x422.jpg",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "2df7460b4957e6eb0c70339499e87d06"
            },
            {
              "title": "NBA: Pelicans' Zion Williamson, Brandon Ingram exit with injuries",
              "author": "Reuters",
              "published_date": "2022-10-24 23:12:14",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482556",
              "clean_url": "inquirer.net",
              "excerpt": "New Orleans Pelicans star forwards Zion Williamson and Brandon Ingram sustained injuries during Sunday night's 122-121 overtime loss to the visiting Utah Jazz. Williamson scored 25 points",
              "summary": "Zion Williamson #1 of the New Orleans Pelicans reacts during the second half of a game against the Utah Jazz at the Smoothie King Center on October 23, 2022 in New Orleans, Louisiana. Jonathan Bachman/Getty Images/AFP\nNew Orleans Pelicans star forwards Zion Williamson and Brandon Ingram sustained injuries during Sunday night's 122-121 overtime loss to the visiting Utah Jazz.\nWilliamson scored 25 points before going to the bench for good midway through the fourth quarter after taking a hard fall and having his hip or back checked by trainers.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/063_1436000254.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "706bd1a5027217800c272cac6fd730a3"
            },
            {
              "title": "Partial operations at Mactan Cebu airport may resume by Tuesday",
              "author": "",
              "published_date": "2022-10-24 23:09:00",
              "published_date_precision": "timezone unknown",
              "link": "https://cebudailynews.inquirer.net/471014/partial-operations-at-mactan-cebu-airport-may-resume-by-tuesday",
              "clean_url": "inquirer.net",
              "excerpt": "CEBU CITY, Philippines - Partial operations at the Mactan-Cebu International Airport (MCIA) may resume by Tuesday, Oct. 25, airport officials said.In a press briefing on Monday, Oct. 24,",
              "summary": "Operations at the Mactan Cebu International Airport (MCIA) remain suspended. No flights are allowed to depart or land on the runway following an accident involving Korean Air Flight KE 631. | 📸Nagiel Bañacia / Facebook\nCEBU CITY, Philippines – Partial operations at the Mactan-Cebu International Airport (MCIA) may resume by Tuesday, Oct. 25, airport officials said.\nIn a press briefing on Monday, Oct. 24, authorities from the Mactan-Cebu International Airport Authority (MCIAA) said they are doing their best to remove Korean Air flight KE631 from the runway by midnight on Tuesday so they can reopen the airport to accommodate smaller aircrafts.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "",
              "media": "https://cebudailynews.inquirer.net/files/2022/10/312812921_485603253599691_8438272356923005351_n-1024x768.jpeg",
              "is_opinion": false,
              "twitter_account": "@cebudailynews",
              "_score": null,
              "_id": "7db429f03ba5295954be3c7357768639"
            },
            {
              "title": "NBA: Jazz stun Pelicans in OT for 3-0 start",
              "author": "Agence France-Presse",
              "published_date": "2022-10-24 23:04:32",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482553",
              "clean_url": "inquirer.net",
              "excerpt": "Lauri Markkanen scored 31 points and Kelly Olynyk made a layup with 3.1 seconds left in overtime as the visiting Utah Jazz defeated the New Orleans Pelicans 122-121 on Sunday night. Markkanen",
              "summary": "Jordan Clarkson #00 of the Utah Jazz reacts after scoring during overtime at the Smoothie King Center on October 23, 2022 in New Orleans, Louisiana. Jonathan Bachman/Getty Images/AFP\nLauri Markkanen scored 31 points and Kelly Olynyk made a layup with 3.1 seconds left in overtime as the visiting Utah Jazz defeated the New Orleans Pelicans 122-121 on Sunday night.\nMarkkanen added 12 rebounds, Olynyk finished with 20 points, Jordan Clarkson scored 18 and Jarred Vanderbilt added 15 points as the Jazz prevailed in a pairing of teams that had both won their first two games.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Agence France-Presse",
              "media": "https://sports.inquirer.net/files/2022/10/063_1435999818.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "20fbb9bde8481319b974c4119ee5b0b4"
            },
            {
              "title": "Top 10 Filipino Celebrities with the most earnings on Instagram",
              "author": "Please Enter Your Name Here",
              "published_date": "2022-10-24 23:00:38",
              "published_date_precision": "full",
              "link": "https://sugbo.ph/2022/filipino-celebrities-instagram/",
              "clean_url": "sugbo.ph",
              "excerpt": "Social media influencers are born through social media. Some became famous for odd reasons. With the mix of commercialization as marketing experts used this as a medium to reach larger audiences —…",
              "summary": "Social media influencers are born through social media. Some became famous for odd reasons. With the mix of commercialization as marketing experts used this as a medium to reach larger audiences — this is where social media influencers came to play. \nFamous brands are tapping influencers to reach their target audiences. This is when social media influencers started to earn huge bucks of money. Ultimately, some attained the peak of their prime and success using these platforms.\nPhoto from NetCredit Website\nInfluencers are all over the globe.",
              "rights": "sugbo.ph",
              "rank": 502829,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Kaye,Please Enter Your Name Here",
              "media": "https://sugbo.ph/wp-content/uploads/2022/10/1-Top-10-IG-Earners-1.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "4c708bf587087177f75ac0fa1e4a21ea"
            },
            {
              "title": "3 Great Pizza Places in New Mexico  Alina Andras",
              "author": "Alina Andras",
              "published_date": "2022-10-24 23:00:00",
              "published_date_precision": "timezone unknown",
              "link": "https://original.newsbreak.com/@alina-andras-1592631/2797506749384-3-great-pizza-places-in-new-mexico",
              "clean_url": "newsbreak.com",
              "excerpt": "If you live in New Mexico and you also happen to love pizza then keep on reading because this article is fo you. Below I have put together a list of three amazing pizza spots in New Mexico that are…",
              "summary": "Storyteller with over 8 years of practical experience. Albuquerque, NMIf you live in New Mexico and you also happen to love pizza then keep on reading because this article is fo you. Below I have put together a list of three amazing pizza spots in New Mexico that are known for their impeccable service and absolutely delicious food.3 Great Pizza Places in New Mexico Giovanni's Pizzeria, Albuquerque Angel Fired Pizza, Angel Fire Pizza Barn, Edgewood Now, what are your thoughts on these amazing pizz",
              "rights": "newsbreak.com",
              "rank": 4828,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Alina Andras",
              "media": "https://img.particlenews.com/img/id/0FGuRo_0ikq5g4r00?type=thumbnail_1600x1200",
              "is_opinion": false,
              "twitter_account": "@newsbreak",
              "_score": null,
              "_id": "fcb0b52af39636ca9438494778c1aef6"
            },
            {
              "title": "2021 GUIDE: Bojo River Cruise and Aloguinsan River Eco-Cultural Tour",
              "author": "Ram Mancelita",
              "published_date": "2022-10-24 22:52:41",
              "published_date_precision": "full",
              "link": "https://sugbo.ph/2021/bojo-river-tour-aloguinsan/",
              "clean_url": "sugbo.ph",
              "excerpt": "If you think you have already witnessed all the captivating beauty of Southern Cebu without visiting Aloguinsan yet, think again. Prepare to be amazed and experience Cebu's very own huge lagoon ala El…",
              "summary": "If you think you have already witnessed all the captivating beauty of Southern Cebu without visiting Aloguinsan yet, think again. Prepare to be amazed and experience Cebu's very own huge lagoon ala El Nido, Palawan!\nBojo River is Aloguinsan's crown jewel and has thus far been named one of the Top 100 Sustainable Destinations in the World on the occasion of World Tourism Day 2016 and Best Community-based Tourism at the ASEAN Toursim Awards 2017.\nThe Bojo River tour, also known as the Aloguinsan River Eco-Cultural Tour, is highlighted by a ride on the river with local fishermen interpreting the local history, the flora and the fauna of the river ecosystem.",
              "rights": "sugbo.ph",
              "rank": 502829,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Please Enter Your Name Here,Ram Mancelita",
              "media": "https://sugbo.ph/wp-content/uploads/2021/01/2-bojo-river-aloguinsan-tour-cebu.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "fd4a9236bfc1261ea357c019929e2f9f"
            },
            {
              "title": "2 drug suspects nabbed in Cavite, Quezon provinces",
              "author": "Delfin T. Mallari Jr.",
              "published_date": "2022-10-24 22:40:39",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/?p=1684127",
              "clean_url": "inquirer.net",
              "excerpt": "LUCENA CITY — Police arrested Sunday two alleged notorious drug traders and seized more than P74,000 worth of \"shabu\" (crystal meth) in buy-bust operations in Cavite and Quezon",
              "summary": "INQUIRER FILE PHOTO\nLUCENA CITY — Police arrested Sunday two alleged notorious drug traders and seized more than P74,000 worth of 'shabu' (crystal meth) in buy-bust operations in Cavite and Quezon provinces.\nThe Cavite police reported that anti-illegal drug operatives in Dasmariñas City collared at 11:50 a.m. Valentino dela Cruz, an alleged member of a local drug syndicate after he sold a sachet of meth to an undercover cop in Barangay Luzviminda 2.\nThe suspect yielded two sachets of shabu with an estimated Dangerous Drugs Board (DDB) value of P42,800.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Delfin T. Mallari Jr.",
              "media": "https://newsinfo.inquirer.net/files/2022/10/quezon-province-arrest-drugs-filephoto-101122-620x349.png",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "861a617612d27ab5c6e2398e7919e2f3"
            },
            {
              "title": "Mactan Cebu International Airport runway open for limited time",
              "author": "Gma News",
              "published_date": "2022-10-24 22:27:47",
              "published_date_precision": "full",
              "link": "https://www.gmanetwork.com/news/topstories/regions/849155/mactan-cebu-international-airport-runway-open-for-limited-time/story/",
              "clean_url": "gmanetwork.com",
              "excerpt": "The Mactan Cebu International Airport runway has been opened again but only during the daytime, according to the report of Mao dela Cruz on Super Radyo DZBB.",
              "summary": "Published October 25, 2022 6:27am A Korean Air plane overshot a runway in Mactan-Cebu International Airport (MCIA) on Sunday evening due to bad weather, but no casualties were reported. FILE PHOTO The Mactan Cebu International Airport runway has been opened again but only during the daytime, according to the report of Mao dela Cruz on Super Radyo DZBB. The runway will be open from 5 a.m. to 5 p.m. for 14 days. There will be no night operations until the runway has been cleared and lights repaired or replaced.",
              "rights": " Copyright 2022 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
              "rank": 5469,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "GMA News,GMA News Online,If Storyparsed.Issaf",
              "media": "https://images.gmanews.tv/webpics/2022/10/koreanair_2022_10_24_07_29_05.jpg",
              "is_opinion": false,
              "twitter_account": "@GMANewsOnline",
              "_score": null,
              "_id": "0c83a109ce76a3061aeb62001b50b6df"
            },
            {
              "title": "K-pop group Tomorrow X Together arrives early in Manila for two-day concert",
              "author": "Jonathan Hic",
              "published_date": "2022-10-24 22:26:04",
              "published_date_precision": "full",
              "link": "https://mb.com.ph/2022/10/25/k-pop-group-tomorrow-x-together-arrives-early-in-manila-for-two-day-concert/",
              "clean_url": "mb.com.ph",
              "excerpt": "K-pop boy band Tomorrow X Together (TXT) arrived in Manila on Oct. 24, several days before their concert. \n\n\n\nTXT (Twitter)\n\n\n\nNetizens posted photos and videos of the boy band's arrival at the Ninoy Aquino International Airport Monday afternoon. \n\n\n\nTXT will hold their 'Act: Love Sick' concert in M",
              "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n \n\nCelebrities, Entertainment, Entertainment News, Music \n\n\nK-pop boy band Tomorrow X Together (TXT) arrived in Manila on Oct. 24, several days before their concert. \nTXT (Twitter)\nNetizens posted photos and videos of the boy band's arrival at the Ninoy Aquino International Airport Monday afternoon. \nTXT will hold their 'Act: Love Sick' concert in Manila on Oct. 27 and 28 at the Mall of Asia Arena. \n\ny'all my cousin works at the airport and saw txt, idk if they're leaving or just arrived here in manila but i hope they stay safe, and im so jealous.",
              "rights": "mb.com.ph",
              "rank": 5693,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Jonathan Hicap",
              "media": "https://files.mb.com.ph/wp-content/uploads/2022/10/25061810/TXT2.jpeg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "c2663f06cf4a7adc1e98ce1184d41579"
            },
            {
              "title": "Yoga: Breathing in the present moment",
              "author": "",
              "published_date": "2022-10-24 22:20:24",
              "published_date_precision": "timezone unknown",
              "link": "https://cebudailynews.inquirer.net/?p=470880",
              "clean_url": "inquirer.net",
              "excerpt": "CEBU CITY, Philippines— 'Dawata.'This is one of the most powerful Cebuano words one can say.'Dawata' means receive.To receive whatever comes your way, to receive what you deserve and",
              "summary": "| Photo from Dawata Yoga Wellness Studio\nCEBU CITY, Philippines— 'Dawata.'\nThis is one of the most powerful Cebuano words one can say.\n'Dawata' means receive.\nTo receive whatever comes your way, to receive what you deserve and to receive the peace you've been wanting to have in your life.\nSepfry Grace Rivera, 33, owner of Dawata Yoga Wellness Studio talks about  the many things people should know about yoga.\n|Photo from Sefry Grace IG\nYoga is not just a practice for flexible people, it is a practice for everyone.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "",
              "media": "https://cebudailynews.inquirer.net/files/2022/10/10-23-yoga-1024x1024.jpeg",
              "is_opinion": false,
              "twitter_account": "@cebudailynews",
              "_score": null,
              "_id": "a2a998ee881195d70d99167d9e99c3bf"
            },
            {
              "title": "CEMEX, PCX, and Greencycle enter into an agreement toward climate action",
              "author": "Inquirer.Net Brandroom",
              "published_date": "2022-10-24 22:14:16",
              "published_date_precision": "timezone unknown",
              "link": "https://globalnation.inquirer.net/?p=207831",
              "clean_url": "inquirer.net",
              "excerpt": "CEMEX Philippines signed a tripartite agreement with Plastic Credit Exchange (PCX) and Greencycle to further strengthen its commitment to reduce its carbon footprint and contribute to a circular",
              "summary": "CEMEX Philippines signed a tripartite agreement with Plastic Credit Exchange (PCX) and Greencycle to further strengthen its commitment to reduce its carbon footprint and contribute to a circular economy. \nThe agreement supports end-to-end plastic waste reduction processes, starting from plastic waste collection, consolidation, aggregation, treatment, and concluding in co-processing, preventing them from ending up in landfills, bodies of water, or the environment. \n'We are very pleased to enter into this agreement which demonstrates our pivotal role in a circular economy, further strengthening our track towards carbon neutrality by 2050,' said Luis Franco, President and CEO of CEMEX Philippines.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "INQUIRER.net BrandRoom",
              "media": "https://globalnation.inquirer.net/files/2022/10/6649A320-CAC1-4F62-8288-7E65C18BC0F1-620x281.png",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "034fd99f838ff66d5486898071a0d384"
            },
            {
              "title": "Murder suspect dead after ‘shootout' with cops in Albay town",
              "author": "Ma. ril Mier-Manjares",
              "published_date": "2022-10-24 21:57:08",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/1684110/murder-suspect-dead-after-shootout-with-cops-in-albay-town",
              "clean_url": "inquirer.net",
              "excerpt": "LEGAZPI CITY — A man being served with arrest warrants was killed Sunday, Oct. 23, in an armed confrontation with police officers in Pio Duran town in Albay province. In a report Monday,",
              "summary": "INQUIRER FILE PHOTO\nLEGAZPI CITY — A man being served with arrest warrants was killed Sunday, Oct. 23, in an armed confrontation with police officers in Pio Duran town in Albay province.\nIn a report Monday, Lieutenant Colonel Maria Luisa Calubaquib, Bicol police spokesperson, said Jun Arellano shot police officers serving arrest warrants around 1:40 p.m. in Barangay Malidong, prompting the lawmen to retaliate.\nArellano suffered bullet wounds and was taken to Pio Duran District Memorial Hospital but died along the way.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Ma. April Mier-Manjares",
              "media": "https://newsinfo.inquirer.net/files/2022/10/albay-dead-filephoto-102422-620x349.png",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "4676ea39577ff99962d9e6a6e58f22c2"
            },
            {
              "title": "US student test results show toll of pandemic lockdowns on learning",
              "author": "Rami Ayyub",
              "published_date": "2022-10-24 21:56:39",
              "published_date_precision": "full",
              "link": "https://www.gmanetwork.com/news/topstories/world/849154/us-student-test-results-show-toll-of-pandemic-lockdowns-on-learning/story/",
              "clean_url": "gmanetwork.com",
              "excerpt": "US students have suffered historic learning setbacks with math and reading scores falling to their lowest levels since before the COVID-19 pandemic, national exam results released on Monday showed,…",
              "summary": "Published October 25, 2022 5:56am Math scores saw their largest drop on record, a trend consistent across most US states and almost all demographic groups, according to the National Assessment of Educational Progress (NAEP), also known as the \"Nation's Report Card.\" FILE PHOTO US students have suffered historic learning setbacks with math and reading scores falling to their lowest levels since before the COVID-19 pandemic, national exam results released on Monday showed, the latest sign of the damage school closures wrought on children.",
              "rights": " Copyright 2022 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
              "rank": 5469,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "If Storyparsed.Issaf,RAMI AYYUB,Reuters",
              "media": "https://images.gmanews.tv/webpics/2018/11/US_flag_statue_of_freedom_2018_11_03_01_59_41.JPG",
              "is_opinion": false,
              "twitter_account": "@GMANewsOnline",
              "_score": null,
              "_id": "fd1edd8934f6b5ef20cb00a363675a51"
            },
            {
              "title": "Lone winner hits P188.4-M Lotto 6/49 jackpot",
              "author": "",
              "published_date": "2022-10-24 21:55:06",
              "published_date_precision": "timezone unknown",
              "link": "https://cebudailynews.inquirer.net/?p=470977",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — One bettor won the Super Lotto 6/49 jackpot prize of over P188 million, the Philippine Charity Sweepstakes Office (PSCO) announced on Monday.The winning combination",
              "summary": "MANILA, Philippines — One bettor won the Super Lotto 6/49 jackpot prize of over P188 million, the Philippine Charity Sweepstakes Office (PSCO) announced on Monday.\nThe winning combination  09-03-19-13-20-20 had a jackpot of P188,471,378.80.\nThe winning ticket, according to the PCSO, was purchased in Guiguinto, Bulacan.\nA total of 171 bets won P50,000 for having five of the sox winning numbers, while 5,683 bets won P1,200 each for having four of the six winning numbers.\nRELATED STORIES\n\nPCSO says Grand Lotto winners were ‘loyal to their numbers'\nBettor from Moalboal, Cebu wins P28.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "",
              "media": "https://cebudailynews.inquirer.net/files/2022/10/10-24-lotto.png",
              "is_opinion": false,
              "twitter_account": "@cebudailynews",
              "_score": null,
              "_id": "52148904aaea4ea2b97203c3abe9ad70"
            },
            {
              "title": "Comic actor Leslie Jordan, 67, killed in Hollywood car accident",
              "author": "Steve Gorman",
              "published_date": "2022-10-24 21:04:22",
              "published_date_precision": "full",
              "link": "https://www.gmanetwork.com/news/showbiz/showbizabroad/849153/comic-actor-leslie-jordan-67-killed-in-hollywood-car-accident/story/",
              "clean_url": "gmanetwork.com",
              "excerpt": "Comic actor Leslie Jordan, a prime-time Emmy winner for his role on the hit sitcom \"Will & Grace\" and a social media sensation during the COVID-19 pandemic, died on Monday in a car crash while driving…",
              "summary": "Published October 25, 2022 5:04am Updated October 25, 2022 6:05am US actor Leslie Jordan arrives for the White House Correspondents' Association gala at the Washington Hilton Hotel in Washington, DC, on April 30, 2022. Stefani Reynolds / AFP LOS ANGELES - Comic actor Leslie Jordan, a prime-time Emmy winner for his role on the hit sitcom \"Will & Grace\" and a social media sensation during the COVID-19 pandemic, died on Monday in a car crash while driving to work in Hollywood, a spokesperson said. He was 67.",
              "rights": " Copyright 2022 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
              "rank": 5469,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "If Storyparsed.Issaf,Reuters,STEVE GORMAN",
              "media": "https://images.gmanews.tv/webpics/2022/10/000_329A6DM_2022_10_25_05_01_40.jpg",
              "is_opinion": false,
              "twitter_account": "@gmanews",
              "_score": null,
              "_id": "589264aee949d380e80c08f407b6b33f"
            },
            {
              "title": "Korean Air overshoots Mactan Cebu airport runway, no casualties reported",
              "author": "",
              "published_date": "2022-10-24 21:01:25",
              "published_date_precision": "timezone unknown",
              "link": "https://cebudailynews.inquirer.net/470964/korean-air-overshoots-at-mactan-cebu-airport-no-casualties-reported",
              "clean_url": "inquirer.net",
              "excerpt": "CEBU CITY, Philippines - Operations at the Mactan-Cebu International Airport (MCIA) remain suspended as of Monday, Oct. 24, after Korean Air flight KE631 overshoot the runway apparently due to bad",
              "summary": "LOOK: Korean Air flight #KE631 overshot its runway at the Mactan-Cebu International Airport late night on Sunday, Oct. 23. In a Facebook post, Lapu-Lapu City DRMMO head Nagiel Bañacia said airport operations remain suspended following the incident. | Photo by Nagiel Bañacia /Facebook\nCEBU CITY, Philippines – Operations at the Mactan-Cebu International Airport (MCIA) remain suspended as of Monday, Oct. 24, after Korean Air flight KE631 overshoot the runway apparently due to bad weather.\nAirport authorities confirmed that an Airbus 330 widebody jet owned and operated by Korean Air overran the runway at 11:11 p.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "",
              "media": "https://cebudailynews.inquirer.net/files/2022/10/309549384_485507400275943_5827638561509667288_n-1024x768.jpeg",
              "is_opinion": false,
              "twitter_account": "@cebudailynews",
              "_score": null,
              "_id": "05cb6315d13a589f55aabcf0ce0812ef"
            },
            {
              "title": "PNP debunks Bantag claim: BuCor properly informed about middleman at NBP",
              "author": "Gabriel Pabico Lalu",
              "published_date": "2022-10-24 20:58:22",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/?p=1684412",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — The Philippine National Police (PNP) has maintained that it properly informed the Bureau of Corrections (BuCor) that the alleged middleman in the Percy Lapid murder case is",
              "summary": "Philippine National Police chief Gen. Rodolfo Azurin Jr. FILE PHOTO\nMANILA, Philippines — The Philippine National Police (PNP) has maintained that it properly informed the Bureau of Corrections (BuCor) that the alleged middleman in the Percy Lapid murder case is detained at the latter's facilities.\nAs to whether the initial coordination reached suspended BuCor director general Gerald Bantag, PNP chief Gen. Rodolfo Azurin Jr. said during Monday's press briefing that they are not aware of it.\nAzurin was asked about Bantag's comments that they could have secured the inmate at the New Bilibid Prison (NBP) — a certain Cristito Villamor who was identified by gunman Joel Escorial as the middleman.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Gabriel Pabico Lalu",
              "media": "https://newsinfo.inquirer.net/files/2022/09/350757-620x428.jpeg",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "bf8ba72970caf427ba18f54017867277"
            },
            {
              "title": "Three dead as Roslyn's intense rains, winds hit Mexico's Pacific coast",
              "author": "Lizbeth Diaz",
              "published_date": "2022-10-24 20:57:41",
              "published_date_precision": "full",
              "link": "https://www.gmanetwork.com/news/topstories/world/849152/three-dead-as-roslyn-s-intense-rains-winds-hit-mexico-s-pacific-coast/story/",
              "clean_url": "gmanetwork.com",
              "excerpt": "At least three people died from destruction caused by intense rainfall unleashed by Storm Roslyn, which provoked flooding along Mexico's Pacific coast when it made landfall as a powerful hurricane on…",
              "summary": "By LIZBETH DIAZ, SARAH MORLAND, Reuters Published October 25, 2022 4:57am A woman and her son walk on the rubble inside a house following the passing of Hurricane Roslyn that hit the Mexico's Pacific coast with heavy winds and rain in Rosamorada in Nayarit state, Mexico, October 23, 2022. REUTERS/Christian Garcia MEXICO CITY - At least three people died from destruction caused by intense rainfall unleashed by Storm Roslyn, which provoked flooding along Mexico's Pacific coast when it made landfall as a powerful hurricane on Sunday.",
              "rights": " Copyright 2022 GMA Network and www.gmanetwork.com/news. Unauthorized use and/or duplication of this material without express and written permission from this site's owner is strictly prohibited. Excerpts and links may be used, provided that full and clear credit is given to GMA Network and GMA News Online with appropriate and specific direction to the original content.",
              "rank": 5469,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "If Storyparsed.Issaf,LIZBETH DIAZ,SARAH MORLAND",
              "media": "https://images.gmanews.tv/webpics/2022/10/2022-10-24T055422Z_1304251825_RC297X9RV5O1_RTRMADP_3_STORM-ROSLYN_2022_10_25_04_55_07.JPG",
              "is_opinion": false,
              "twitter_account": "@gmanews",
              "_score": null,
              "_id": "40183b5a0c52f00234515fd95b136151"
            },
            {
              "title": "Racists should be banned from stadiums, says Real Madrid's Vinicius Jr.",
              "author": "Reuters",
              "published_date": "2022-10-24 20:46:31",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482598",
              "clean_url": "inquirer.net",
              "excerpt": "MADRID - Real Madrid forward Vinicius Jr. believes that fans found guilty of racist abuse should be banned for life from attending games. The 22-year-old Brazilian was a victim of abuse in",
              "summary": "Real Madrid's Brazilian forward Vinicius Junior (R) fights for the ball with Sevilla's Spanish defender Jose Angel Carmona (L) and Sevilla's Moroccan goalkeeper Yassine Bounou 'Bono' (Down) during the Spanish league football match between Real Madrid CF and Sevilla FC at the Santiago Bernabeu stadium in Madrid, on October 22, 2022. (Photo by JAVIER SORIANO / AFP)\nMADRID – Real Madrid forward Vinicius Jr. believes that fans found guilty of racist abuse should be banned for life from attending games.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/000_32LX8FK.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "60ceaaffcbdf2f22e13161b5758af619"
            },
            {
              "title": "Family members of Percy Lapid face threats amid investigation",
              "author": "Zacarian Sarao",
              "published_date": "2022-10-24 20:40:46",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/1684405/family-members-of-percy-lapid-face-threats-amid-investigation",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — Given the ongoing investigation into the killing of radio commentator Percy Lapid, his family members had been receiving threats and extortion attempts, according to his",
              "summary": "CALL FOR PRUDENCE The family of journalist Percival 'Percy Lapid' Mabasa asked the police to be cautious in investigating his murder on Oct. 3. Visiting his wake at Manila Memorial Park in Parañaque City on Wednesday, Philippine National Police chief Gen. Rodolfo Azurin Jr. said there were 'different persons of interest' but no suspect yet in the killing. —GRIG C. MONTEGRANDE\nMANILA, Philippines — Given the ongoing investigation into the killing of radio commentator Percy Lapid, his family members had been receiving threats and extortion attempts, according to his brother Roy Mabasa.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Zacarian Sarao",
              "media": "https://newsinfo.inquirer.net/files/2022/10/363233-620x413.jpeg",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "98277e7e758b89db591b4948fea94b00"
            },
            {
              "title": "Man United shows future is brighter without Cristiano Ronaldo",
              "author": "Reuters",
              "published_date": "2022-10-24 20:40:40",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482595",
              "clean_url": "inquirer.net",
              "excerpt": "MANCHESTER, England - Manchester United may not have won their first game since banishing Cristiano Ronaldo from the squad but Saturday's 1-1 draw at Chelsea seemed to confirm the belief they",
              "summary": "FILE PHOTO: Soccer Football – Premier League – Manchester United v Newcastle United – Old Trafford, Manchester, Britain – October 16, 2022 Manchester United's Cristiano Ronaldo reacts after a goal he scored is disallowed REUTERS/David Klein/File Photo\nMANCHESTER, England – Manchester United may not have won their first game since banishing Cristiano Ronaldo from the squad but Saturday's 1-1 draw at Chelsea seemed to confirm the belief they are better off without the individualistic superstar.\nAlthough they needed a 94th-minute strike from Casemiro to rescue a point, United was dominant for large parts of the game and looked far more cohesive without the five-times world player of the year.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/2022-10-24T114303Z_1_LYNXMPEI9N0FC_RTROPTP_4_SOCCER-ENGLAND-MUN-NEW-REPORT-scaled.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "3165a4be37d94f4b611448b10d0a8908"
            },
            {
              "title": "NBA: Lakers squander late lead in loss to Trail Blazers",
              "author": "Agence France-Presse",
              "published_date": "2022-10-24 20:40:14",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482543",
              "clean_url": "inquirer.net",
              "excerpt": "LOS ANGELES - Damian Lillard scored 41 points and Jeremi Grant drove for a game-winning layup with three seconds left Sunday as the Portland Trail Blazers dealt the Los Angeles Lakers their third",
              "summary": "Damian Lillard of the Portland Trail Blazers looks to pass the ball under pressure from Patrick Beverley and Anthony Davis of the Los Angeles Lakers during the first half of the game at Crypto.com Arena on October 23, 2022 in Los Angeles, California.  (Getty Images via AFP)\nLOS ANGELES – Damian Lillard scored 41 points and Jeremi Grant drove for a game-winning layup with three seconds left Sunday as the Portland Trail Blazers dealt the Los Angeles Lakers their third defeat to open the NBA season.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Agence France-Presse",
              "media": "https://sports.inquirer.net/files/2022/10/063_1244181915-scaled.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "9bce11f77431c69f77d697e32e864d0c"
            },
            {
              "title": "UP Vanguard Centennial Agribusiness webinar",
              "author": "Dr. Bernardo M. Villegas",
              "published_date": "2022-10-24 20:31:00",
              "published_date_precision": "full",
              "link": "https://mb.com.ph/2022/10/25/up-vanguard-centennial-agribusiness-webinar/",
              "clean_url": "mb.com.ph",
              "excerpt": "(PART 1)\n\n\n\n\n\n\n\n Last October 15, 2022, I participated in a very stimulating webinar organized by the UP Vanguard Alumni on the occasion of the 100th Anniversary of their organization. The theme of the webinar was 'Investing in Food, Nutrition, and Preventive Health Security for the",
              "summary": "More from us:\n\n\nPressReader \n\n\n\n\n\n\n\n\n\n\n\n \n \n\n\n\n\n\n\n \n\n(PART 1)\n\n\n                Last October 15, 2022, I participated in a very stimulating webinar organized by the UP Vanguard Alumni on the occasion of the 100th Anniversary of their organization.  The theme of the webinar was 'Investing  in Food, Nutrition, and Preventive Health Security for the Next 100 Years.'  Of course, the reason the organizers chose such a long time horizon was to match the centennial they were celebrating.  All the speakers, though, had a shorter time horizon in presenting their respective recommendations to achieve food security.",
              "rights": "mb.com.ph",
              "rank": 5693,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Dr. Bernardo M. Villegas",
              "media": "https://mb.com.ph/wp-content/uploads/2020/07/lugtu.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "ba1bd12f9936a862bf1a772e59467727"
            },
            {
              "title": "BJMP personnel serving in BuCor to return to mother unit — DOJ chief",
              "author": "Tetch Torres-Tupas",
              "published_date": "2022-10-24 20:19:28",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/1684395/bjmp-personnel-serving-at-bucor-to-return-to-mother-unit-doj-chief",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines -- Justice Secretary Jesus Crispin \"Boying\" Remulla on Monday said personnel from the Bureau of Jail Management and Penology (BJMP) that were deployed at the Bureau",
              "summary": "Facade of the New Bilibid Prison (NBP), with the Bureau of Corrections (BuCor) sign. Image from the BuCor website\nMANILA, Philippines — Justice Secretary Jesus Crispin 'Boying' Remulla on Monday said personnel from the Bureau of Jail Management and Penology (BJMP) that were deployed at the Bureau of Corrections (BuCor) might soon return to their mother unit.\nBJMP personnel were deployed at BuCor following the appointment of Gerald Bantag in 2019. A memorandum of agreement was signed between BuCor and BJMP to augment BuCor personnel and help institute reforms at the controversial government bureau.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Tetch Torres-Tupas",
              "media": "https://newsinfo.inquirer.net/files/2020/04/BuCor-620x289.png",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "f2164be5906ac2b29492a76a7cae9e82"
            },
            {
              "title": "BANGSAMORO VETERAN MUJAHIDEEN AFFAIRS OFFICE PROPOSED IN BARMM",
              "author": "Julmunir Jannaral",
              "published_date": "2022-10-24 20:15:00",
              "published_date_precision": "timezone unknown",
              "link": "https://www.manilatimes.net/2022/10/25/news/regions/bangsamoro-veteran-mujahideen-affairsoffice-proposed-in-barmm/1863535",
              "clean_url": "manilatimes.net",
              "excerpt": "COTABATO CITY: The Bangsamoro Parliament is pushing for the establishment of an office that will provide assistance to underprivileged veteran mujahideen in the region. A...",
              "summary": "COTABATO CITY: The Bangsamoro Parliament is pushing for the establishment of an office that will provide assistance to underprivileged veteran mujahideen in the region. A Bangsamoro Veteran Mujahideen Affairs Office (BVMAO) will be established under a proposed measure refiled by the Bangsamoro government to provide financial, medical, social, and other assistance to Moro Islamic Liberation Front and Moro National Liberation Front veterans who have rendered revolutionary services in the protracted wars for self-determination \"between the Bangsamoro people and the National Government\" for at least 20 years.",
              "rights": "manilatimes.net",
              "rank": 7400,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Julmunir Jannaral",
              "media": "https://cdn4.premiumread.com/?url=https://www.manilatimes.net/theme_manilatimes/images/TMTFB_1920x1008.jpg&w=1920&q=100&f=webp",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "b5d932098306c833754d9922b57f8fd9"
            },
            {
              "title": "BAGUIO MULLS ASSISTANCE PROGRAM TO HELP LOCAL FARMERS, FISHERFOLK",
              "author": "Gab. Keith",
              "published_date": "2022-10-24 20:15:00",
              "published_date_precision": "timezone unknown",
              "link": "https://www.manilatimes.net/2022/10/25/news/regions/baguio-mulls-assistance-program-to-help-local-farmers-fisherfolk/1863532",
              "clean_url": "manilatimes.net",
              "excerpt": "BAGUIO CITY: Acting city mayor Faustino Olowan signed City Council Resolution 457-22 requesting the City Veterinary and Agriculture Office (CVAO) to plan and implement a marketing...",
              "summary": "BAGUIO CITY: Acting city mayor Faustino Olowan signed City Council Resolution 457-22 requesting the City Veterinary and Agriculture Office (CVAO) to plan and implement a marketing assistance program that will increase the marketing and entrepreneurial capacities of urban farmers and fisherfolk in the Summer Capital. This is through the provision of transportation services to allow them to bring their goods from farm to market and haul inputs from suppliers to their farms. \"The farmers aired their concerns and appealed for interventions that will ease their production and postharvest activities such as the provision of vehicles or transportation services from their farms to the market.",
              "rights": "manilatimes.net",
              "rank": 7400,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "B. Keith,Gab. Keith",
              "media": "https://cdn4.premiumread.com/?url=https://www.manilatimes.net/theme_manilatimes/images/TMTFB_1920x1008.jpg&w=1920&q=100&f=webp",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "bc3f5dd50aed62e87d7b93abe10b3002"
            },
            {
              "title": "SILANG LGU LAUNCHES FESTIVAL OF SERVICES",
              "author": "Dennis Abrina",
              "published_date": "2022-10-24 20:15:00",
              "published_date_precision": "timezone unknown",
              "link": "https://www.manilatimes.net/2022/10/25/news/regions/silang-lgu-launches-festival-of-services/1863534",
              "clean_url": "manilatimes.net",
              "excerpt": "SILANG, Cavite: The local government here has launched the Festival of Services in a ribbon-cutting ceremony after the flag-raising rites at the New Municipal Hall grounds in...",
              "summary": "SILANG, Cavite: The local government here has launched the Festival of Services in a ribbon-cutting ceremony after the flag-raising rites at the New Municipal Hall grounds in Barangay Biga 1 on Monday, October 24. Among the services offered are free eye checkups, the Tulong Guro program, free haircut for men and women, and other livelihood programs, among others. Mayor Kevin Anarna and Vice Mayor Edward Carranza spearheaded the project.",
              "rights": "manilatimes.net",
              "rank": 7400,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Dennis Abrina",
              "media": "https://cdn4.premiumread.com/?url=https://www.manilatimes.net/theme_manilatimes/images/TMTFB_1920x1008.jpg&w=1920&q=100&f=webp",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "b8c266c59170339f0ea8727ef4080deb"
            },
            {
              "title": "REGIONAL DEVELOPMENT COUNCIL-12 HAS NEW CHAIRPERSON",
              "author": "Asangan Madale",
              "published_date": "2022-10-24 20:15:00",
              "published_date_precision": "timezone unknown",
              "link": "https://www.manilatimes.net/2022/10/25/news/regions/regional-development-council-12has-new-chairperson/1863533",
              "clean_url": "manilatimes.net",
              "excerpt": "THE MUSLIM community welcomed the appointment of North Cotabato Gov. Emmylou Mendoza as the new chairperson for the Regional Development Council-12, who is supportive of the...",
              "summary": "THE MUSLIM community welcomed the appointment of North Cotabato Gov. Emmylou Mendoza as the new chairperson for the Regional Development Council-12, who is supportive of the Southern Philippine peace process. Bangsamoro Labor Minister Muslim Sema, chairman of the Moro National Liberation Front, said other Muslim leaders welcome this development. Mendoza was recently appointed by President Ferdinand Marcos Jr.",
              "rights": "manilatimes.net",
              "rank": 7400,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Asangan Madale",
              "media": "https://www.manilatimes.net/manilatimes/uploads/images/2022/10/24/120203.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "5591728206eb98332085cf93289db18d"
            },
            {
              "title": "Ex-PNP chief joins DOH: ‘Insult to health experts'",
              "author": "",
              "published_date": "2022-10-24 20:09:15",
              "published_date_precision": "timezone unknown",
              "link": "https://cebudailynews.inquirer.net/?p=470956",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — The Department of Health (DOH) on Sunday confirmed the appointment of former Philippine National Police chief Gen. Camilo Cascolan as one of the agency's",
              "summary": "Camilo Cascolan\nMANILA, Philippines — The Department of Health (DOH) on Sunday confirmed the appointment of former Philippine National Police chief Gen. Camilo Cascolan as one of the agency's undersecretaries.\nIn a statement, the DOH said it received the appointment papers of Cascolan and of lawyer Charade Mercado-Grande, who serves as assistant secretary.\nAlso appointed as Director IV are Maria Lourdes Caballero Santiago and Girlie Veloso; and Maria Joyce Ducusin and Sophia Mancao as both Director III.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "",
              "media": "https://cebudailynews.inquirer.net/files/2022/10/10-24-Retired-PNP-Chief-Camilo-Cascolan.jpeg",
              "is_opinion": false,
              "twitter_account": "@cebudailynews",
              "_score": null,
              "_id": "0488328a99541a0f9483c9219ae33dbe"
            },
            {
              "title": "Anji Salvacion, Brent Manalo reminisce their favorite moments in the new music video 'COY' (Cuz of You)",
              "author": "Jessica Ann Evangelista",
              "published_date": "2022-10-24 20:05:52",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/anji-salvacion-brent-manalo-reminisce-their-favorite-moments-in-the-new-music-video-coy-cuz-of-you/",
              "clean_url": "lionheartv.net",
              "excerpt": "In a Zoom presser on October 17, Kapamilya stars Anji Salvacion and Brent Manalo expressed how happy they are to work together in the new music video COY (Cuz of You), a collaboration between Kyla…",
              "summary": "In a Zoom presser on October 17, Kapamilya stars Anji Salvacion and Brent Manalo expressed how happy they are to work together in the new music video COY (Cuz of You), a collaboration between Kyla (Alvarez) and Brian McKnight Jr.\n Written by American artist McKnight Jr., COY (Cuz of You) describes the experience of dating someone and hoping you will be with that person for a long time, despite the distance. \n'Brent and I, it's our first music video together and I just feel so blessed and honored because Tarsier Records trusted us to star in the music video.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Jessica Ann Evangelista",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/Anji-Salvacion-Brent-Manalo.jpg",
              "is_opinion": false,
              "twitter_account": "@lionheartv",
              "_score": null,
              "_id": "8a66625a48b19bccade5c2479829ced9"
            },
            {
              "title": "LPA east of Mindanao may turn into tropical depression in next 48 hours — Pagasa",
              "author": "Zacarian Sarao",
              "published_date": "2022-10-24 20:00:46",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/?p=1684393",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — A low pressure area (LPA) being monitored east of Visayas may escalate into a tropical depression within the next 48 hours, said the Philippine Atmospheric, Geophysical",
              "summary": "Source: DOST / Pagasa\nMANILA, Philippines — A low pressure area (LPA) being monitored east of Visayas may escalate into a tropical depression within the next 48 hours, said the Philippine Atmospheric, Geophysical and Astronomical Services Administration (Pagasa) on Monday.\nAccording to Pagasa weather specialist Grace Castañeda in Pagasa's latest weather advisory, the LPA was last spotted 995 east of Visayas.\n'Itong low pressure area na ito sa kasalukuyan ay wala pa itong direct effects sa ating bansa, ngunit meron itong posibilidad na magdevelop at maging isang bagyo within the next 48 hours,' she said.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Zacarian Sarao",
              "media": "https://newsinfo.inquirer.net/files/2022/10/1-him-colored-26-620x448.png",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "88d9a634908f993b4898a362dce9df06"
            },
            {
              "title": "PBA: ‘Jaworski-like': Scottie Thompson impresses Tim Cone anew",
              "author": "Denison Rey A. Dalupang",
              "published_date": "2022-10-24 19:58:04",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/?p=482592",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines—For his Sonny Jawroski-like workmanship, Barangay Ginebra ace and reigning Most Valuable Player Scottie Thompson was crowned the Philippine Basketball Association Press Corps",
              "summary": "Barangay Ginebra guard Scottie Thompson goes for a shot against Magnolia in the 2022 PBA Commissioner's Cup. PBA IMAGES\nMANILA, Philippines—For his Sonny Jawroski-like workmanship, Barangay Ginebra ace and reigning Most Valuable Player Scottie Thompson was crowned the Philippine Basketball Association Press Corps Player of the Week.\nThompson was among the heroes in the Gin Kings' 103-97 Sunday night conquest of its sister team and fierce rival Magnolia before 12,087 animated souls at Mall of Asia Arena in Pasay City.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Denison Rey A. Dalupang",
              "media": "https://sports.inquirer.net/files/2022/10/Scottie-Thompson-Ginebra-PBA.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "7cd9b5f3b6db2f020df21bdabd5c9d0f"
            },
            {
              "title": "Patricia Tumulak, Emil Sumangil, and Kim Atienza share their techniques for dealing with fake news, haters",
              "author": "Elijah Daniel Espiritu",
              "published_date": "2022-10-24 19:52:53",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/dapat-alam-mo-hosts-share-their-techniques-for-dealing-with-fake-news-haters/",
              "clean_url": "lionheartv.net",
              "excerpt": "Dapat Alam Mo! trio Patricia Tumulak, Emil Sumangil, and Kim Atienza told the press their go-to techniques in dealing with bashers and ‘fake news' at a presser on October 17. The hosts shared…",
              "summary": "Dapat Alam Mo! trio Patricia Tumulak, Emil Sumangil, and Kim Atienza told the press their go-to techniques in dealing with bashers and ‘fake news' at a presser on October 17.\n The hosts shared different insights on their ways to effectively manage haters on their social media spaces. \nSumangil and Tumulak shared similar tips by saying that they divert the attention of people toward good and straight news, while Atienza approaches ‘fake news' by responding with useful trivia.\n'There will always be haters.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Elijah Daniel Espiritu",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/Emil-Sumangil-Kim-Atienza-Patricia-Tumulak.jpg",
              "is_opinion": false,
              "twitter_account": "@lionheartv",
              "_score": null,
              "_id": "1dee4ea7d48113d4f393151a920ffd02"
            },
            {
              "title": "Uncover lies and dark secrets of teenagers as they hide them behind wealth and power in 'Secrets Of A Nympho'",
              "author": "Lion's Den",
              "published_date": "2022-10-24 19:49:18",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/uncover-lies-and-dark-secrets-of-teenagers-as-they-hide-them-behind-wealth-and-power-in-secrets-of-a-nympho/",
              "clean_url": "lionheartv.net",
              "excerpt": "The unexpected death of a young man brings chaos and threatens the reputation of a prestigious school and its students. Uncover lies and dark secrets of teenagers as they hide them behind wealth and…",
              "summary": "The unexpected death of a young man brings chaos and threatens the reputation of a prestigious school and its students. Uncover lies and dark secrets of teenagers as they hide them behind wealth and power. Stream SECRETS OF A NYMPHO on Vivamax starting October 23, 2022.\n At the University of Potenciana, a high-end campus where the best and brightest are only accepted, excellence and greatness are expected from its students, but one tragedy changes everything. During their school's annual bonfire party, where drugs and booze are overflowing, and the students are either too high or too drunk to be aware of their surroundings, Brian (Arron Villaflor), the campus prince, falls off the rooftop and dies.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Lion's Den",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/Secrets-Of-A-Nympho-fI.jpg",
              "is_opinion": false,
              "twitter_account": "@https://www.twittercom/LionhearTVNet",
              "_score": null,
              "_id": "ecfe7d13d914972311a0f388dbac8de5"
            },
            {
              "title": "Marcos Jr. thanks Filipinos, Hawaiians for generosity after family's 1986 exile",
              "author": "Dhne Galvez",
              "published_date": "2022-10-24 19:48:04",
              "published_date_precision": "timezone unknown",
              "link": "https://newsinfo.inquirer.net/1684388/marcos-jr-thanks-filipinos-hawaiians-for-generosity-after-familys-1986-exile",
              "clean_url": "inquirer.net",
              "excerpt": "MANILA, Philippines — President Ferdinand \"Bongbong\" Marcos Jr. on Monday recalled the kindness and generosity of the Filipino community in Hawaii back in 1986 when their family was",
              "summary": "President Ferdinand Marcos Jr. FILE PHOTO\nMANILA, Philippines — President Ferdinand 'Bongbong' Marcos Jr. on Monday recalled the kindness and generosity of the Filipino community in Hawaii back in 1986 when their family was exiled there after his father's ouster from power.\nMarcos Jr. expressed his gratitude today during a courtesy call with officials and members of the Filipino Chamber of Commerce of Hawaii (FCCH) in Malacañang.\n'President Ferdinand R. Marcos recounted the generosity of our kababayans and the Hawaiian people to his family in 1986,' the Office of the President (OP) said in a Facebook post.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Daphne Galvez",
              "media": "https://newsinfo.inquirer.net/files/2022/10/371140-e1666372654227-620x345.jpeg",
              "is_opinion": false,
              "twitter_account": "@inquirerdotnet",
              "_score": null,
              "_id": "bf74a101f96e06ba1864e6033a888ceb"
            },
            {
              "title": "Denise Esteban, Adrian Alandy discussed how they handled the age gap between them as they portrayed as a couple in 'Kara Krus'",
              "author": "RJ Mataro",
              "published_date": "2022-10-24 19:47:53",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/denise-esteban-adrian-alandy-discussed-how-they-handled-the-age-gap-between-them-as-they-portrayed-as-a-couple-in-kara-krus/",
              "clean_url": "lionheartv.net",
              "excerpt": "At the media conference for Kara Krus on October 18, to which LionhearTV got invited, Viva artists Denise Esteban and Adrian Alandy discussed how they handled the age gap when portraying their roles.…",
              "summary": "At the media conference for Kara Krus on October 18, to which LionhearTV got invited, Viva artists Denise Esteban and Adrian Alandy discussed how they handled the age gap when portraying their roles.\n Alandy admitted that portraying a role of a married couple because of their age gap was a challenge for him. \n'‘Yung pinaka-challenge talaga dito is when I first met Denise. It's my first time working with her, ang tinanong ko agad, ‘How old are you?' Kasi, I want to break that barrier na–hindi ko ine-expect na– at that time, Denise, 19 ka, sabi mo sa akin 19 ka, or were you just joking?\n'Medyo kinabahan ako, ilang taon na ko tapos siya nineteen, kailangan magka-rapport agad kami kasi first time namin to work together.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "RJ Mataro",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/Adrian-Alandy-Denise-Esteban.jpg",
              "is_opinion": false,
              "twitter_account": "@rjmataro",
              "_score": null,
              "_id": "f6fb6b8db0ac12a917d4c09b658ab8c3"
            },
            {
              "title": "A movie about love and identity that celebrates being straight as much as being gay in 'Mahal Kita, Beksman'",
              "author": "Lion's Den",
              "published_date": "2022-10-24 19:35:36",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/a-movie-about-love-and-identity-that-celebrates-being-straight-as-much-as-being-gay-in-mahal-kita-beksman/",
              "clean_url": "lionheartv.net",
              "excerpt": "From the creators of 'Die Beautiful' and 'The Panti Sisters', comes a film that will surely entertain not just the LGBTQ community, but the general public. A movie about love and identity that…",
              "summary": "From the creators of 'Die Beautiful' and 'The Panti Sisters', comes a film that will surely entertain not just the LGBTQ community, but the general public. A movie about love and identity that celebrates being straight as much as being gay.\n 'Mahal Kita, Beksman' tells the story of Dali, the only son of Jaime and Gemma (Keempee de Leon and Katya Santos) whom he fondly calls 'Papshiekels and Momshiekels'. Dali is a very talented make-up artist and designer, which is not surprising as his father runs a beauty salon and his mother runs a dress shop.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Lion's Den",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/Mahal-Kita-Beksman-fi.jpg",
              "is_opinion": false,
              "twitter_account": "@lionheartv",
              "_score": null,
              "_id": "1c9165aa14f180bd21874fb8cc42e917"
            },
            {
              "title": "Singaporean talents are joyful to work with Pinoy artists in a collaborative music",
              "author": "Jessica Ann Evangelista",
              "published_date": "2022-10-24 19:33:11",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/singaporean-talents-are-joyful-to-work-with-pinoy-artists-in-a-collaborative-music/",
              "clean_url": "lionheartv.net",
              "excerpt": "ABS-CBN's Star Pop and Singapore's AOR Global collaborated in an extended play (EP), 'My Safe Place,' featuring six tracks from Filipino artists Trisha Denise and LU.ME. and Singaporean talents KIRI,…",
              "summary": "ABS-CBN's Star Pop and Singapore's AOR Global collaborated in an extended play (EP), 'My Safe Place,' featuring six tracks from Filipino artists Trisha Denise and LU.ME. and Singaporean talents KIRI, Kotoji, and Marian Carmel, to advocate mental health through music.\n In a MediaCon on October 17, Singapore-based artists, KIRI, Kotoji, and Marian Carmel shared how happy they are to experience the Filipino ways and the Philippines by working on the cross-cultural project. \n'It's different. I feel like the scale is so much larger.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Jessica Ann Evangelista",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/Filipino-artists-Trisha-Denise-and-LU.ME_.-and-Singaporean-talents-KIRI-kotoji-and-Marian-Carmel.jpg",
              "is_opinion": false,
              "twitter_account": "@lionheartv",
              "_score": null,
              "_id": "bfef3efa0802869a77455a6c241539bb"
            },
            {
              "title": "Southampton holds league-leader Arsenal to 1-1 draw",
              "author": "Reuters",
              "published_date": "2022-10-24 19:32:59",
              "published_date_precision": "timezone unknown",
              "link": "https://sports.inquirer.net/482589/southampton-holds-league-leader-arsenal-to-1-1-draw",
              "clean_url": "inquirer.net",
              "excerpt": "SOUTHAMPTON, England-Granit Xhaka scored a superb early goal but Premier League leaders Arsenal were held to a 1-1 draw by Southampton on Sunday as Stuart Armstrong netted a deserved second-half",
              "summary": "Soccer Football – Premier League – Southampton v Arsenal – St Mary's Stadium, Southampton, Britain – October 23, 2022 Arsenal's Granit Xhaka celebrates scoring their first goal with teammates REUTERS/Dylan Martinez\nSOUTHAMPTON, England-Granit Xhaka scored a superb early goal but Premier League leaders Arsenal were held to a 1-1 draw by Southampton on Sunday as Stuart Armstrong netted a deserved second-half equalizer for the home side.\nThe result moved Arsenal to 28 points from 11 games, two ahead of second-placed Manchester City, while Southampton are 15th with 12 points from 12 games.",
              "rights": "inquirer.net",
              "rank": 1957,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Reuters",
              "media": "https://sports.inquirer.net/files/2022/10/2022-10-23T151044Z_1_LYNXMPEI9M066_RTROPTP_4_SOCCER-ENGLAND-SOU-ARS-REPORT.jpg",
              "is_opinion": false,
              "twitter_account": null,
              "_score": null,
              "_id": "c63cfba9355a12d7f8f6fd327267d0a9"
            },
            {
              "title": "Valladolid residents complain of illegal garbage dumping",
              "author": "Roger Beltran",
              "published_date": "2022-10-24 19:25:14",
              "published_date_precision": "full",
              "link": "https://visayandailystar.com/valladolid-residents-complain-of-illegal-garbage-dumping",
              "clean_url": "visayandailystar.com",
              "excerpt": "BY GILBERT P. BAYORAN As the local government unit of San Enrique continues to retrieve the garbage dumped at a private property in Pulupandan, Negros",
              "summary": "BY GILBERT P. BAYORAN\n\nAs the local government unit of San Enrique continues to retrieve the garbage dumped at a private property in Pulupandan, Negros Occidental, residents of Purok 3 in Brgy. Ayungon, Valladolid, have complained against the illegal dumping of mixed waste by a dump truck allegedly owned by the municipal government of San Enrique.\n\nCelina Segunla, officer in charge of the Valladolid Municipal Environment and Natural Resources Office (MENRO), in her letter to Mayor Enrique Miravalles, attached with the petition letter of concerned residents, said the lot where the garbage is being dumped is owned by San Enrique Mayor Jilson Tubillara.",
              "rights": "visayandailystar.com",
              "rank": 397994,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Roger Beltran",
              "media": "https://visayandailystar.com/wp-content/uploads/2022/10/garbage.jpg",
              "is_opinion": false,
              "twitter_account": "@visayanstar",
              "_score": null,
              "_id": "963cd6aa32319ea8bbe9b5fad00edb0b"
            },
            {
              "title": "MMFF 2022 completes its eight official entries",
              "author": "Lion's Den",
              "published_date": "2022-10-24 19:25:13",
              "published_date_precision": "full",
              "link": "https://www.lionheartv.net/2022/10/mmff-2022-completes-its-eight-official-entries/",
              "clean_url": "lionheartv.net",
              "excerpt": "The biggest, most popular and the widely supported and anticipated 48th Metro Manila Film Festival (MMFF) completes its eight official entries with the selection of the four finished films from a…",
              "summary": "The biggest, most popular and the widely supported and anticipated 48th Metro Manila Film Festival (MMFF) completes its eight official entries with the selection of the four finished films from a record high of 22 film submissions.\n The esteemed members of the Selection Committee headed by the multi-awarded and much respected leader of the film industry Boots Anson-Rodrigo chose the Top 8 based on the following criteria – Artistic Excellence – 40%, Commercial Appeal – 40%, Filipino Cultural Values – 10% and Global Appeal – 10%.",
              "rights": "lionheartv.net",
              "rank": 432685,
              "topic": "news",
              "country": "PH",
              "language": "en",
              "authors": "Lion's Den",
              "media": "https://www.lionheartv.net/wp-content/uploads/2022/10/MMFF-2022-Official-Entries-Announced-FI.jpg",
              "is_opinion": false,
              "twitter_account": "@lionheartv",
              "_score": null,
              "_id": "4f67e2155d5595fdc7dc6bb6552e928a"
            }
          ],
          "user_input": {
            "lang": [
              "en"
            ],
            "not_lang": null,
            "countries": [
              "PH"
            ],
            "not_countries": null,
            "page": 1,
            "size": 50,
            "sources": null,
            "not_sources": null,
            "topic": "news",
            "from": "2022-10-23 23:46:11"
          }
        }
    """.trimIndent()
}
